[package]
name = "adventofcode_2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "intcode"
path = "src/intcode.rs"

[dependencies]
array_tool = "1.0.3"
itertools = "0.10.5"
project-root = "0.2.2"
